"""Add booking constraints

Revision ID: 1c792cedd755
Revises: d3ed2a7fdc70
Create Date: 2026-09-08 23:22:12.908470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c792cedd755'
down_revision: Union[str, Sequence[str], None] = 'd3ed2a7fdc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up duplicate active bookings before applying unique index
    op.execute("""
        UPDATE bookings 
        SET status = 'CANCELLED'
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY farmer_id, slot_id 
                    ORDER BY created_at DESC
                ) as row_num 
                FROM bookings 
                WHERE status != 'CANCELLED'
            ) t 
            WHERE t.row_num > 1
        );
    """)
    op.create_index('idx_unique_active_booking_per_slot', 'bookings', ['farmer_id', 'slot_id'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    op.create_check_constraint(op.f('slots_check_booked_count_capacity_check'), 'slots', 'booked_count <= capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('slots_check_booked_count_capacity_check'), 'slots', type_='check')
    op.drop_index('idx_unique_active_booking_per_slot', table_name='bookings', postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###
