"""Initial Schema

Revision ID: 8fb27180134a
Revises: 
Create Date: 2026-09-02 04:05:44.300621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb27180134a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('centres_pkey'))
    )
    op.create_index(op.f('centres_code_idx'), 'centres', ['code'], unique=True)
    op.create_table('crops',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crops_pkey'))
    )
    op.create_index(op.f('crops_code_idx'), 'crops', ['code'], unique=True)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_phone_idx'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('audit_logs_centre_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('centre_capacity',
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('max_daily_bookings', sa.Integer(), nullable=False),
    sa.Column('processing_lanes', sa.Integer(), nullable=False),
    sa.Column('max_active_queue', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('centre_capacity_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('centre_capacity_pkey'))
    )
    op.create_table('centre_metrics',
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_arrivals', sa.Integer(), nullable=False),
    sa.Column('total_completed', sa.Integer(), nullable=False),
    sa.Column('average_wait_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peak_queue_length', sa.Integer(), nullable=True),
    sa.Column('average_processing_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=True),
    sa.Column('utilization_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('centre_metrics_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('centre_metrics_pkey'))
    )
    op.create_table('farmers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('farmers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('farmers_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('farmers_user_id_key'))
    )
    op.create_table('officers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('officers_centre_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('officers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('officers_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('officers_user_id_key'))
    )
    op.create_table('predictions',
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('prediction_for', sa.DateTime(), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('predictions_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.create_index('idx_predictions_centre_for', 'predictions', ['centre_id', 'prediction_for'], unique=False)
    op.create_table('slots',
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('slots_centre_id_fkey')),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('slots_crop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('slots_pkey'))
    )
    op.create_index('idx_slots_centre_date_time', 'slots', ['centre_id', 'slot_date', 'start_time'], unique=False)
    op.create_table('bookings',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('bookings_centre_id_fkey')),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('bookings_crop_id_fkey')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('bookings_farmer_id_fkey')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('bookings_slot_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('bookings_booking_reference_idx'), 'bookings', ['booking_reference'], unique=True)
    op.create_index('idx_bookings_centre_slot', 'bookings', ['centre_id', 'slot_id'], unique=False)
    op.create_index('idx_bookings_farmer_status', 'bookings', ['farmer_id', 'status'], unique=False)
    op.create_table('farmer_crops',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('estimated_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('farmer_crops_crop_id_fkey')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('farmer_crops_farmer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('farmer_crops_pkey')),
    sa.UniqueConstraint('farmer_id', 'crop_id', 'season', name='uq_farmer_crop_season')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('notifications_booking_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('processing_history',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('processing_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('processing_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('processing_history_booking_id_fkey')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('processing_history_centre_id_fkey')),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('processing_history_crop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_history_pkey'))
    )
    op.create_table('procurements',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tare_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quality_status', sa.String(length=50), nullable=True),
    sa.Column('quality_remarks', sa.Text(), nullable=True),
    sa.Column('procurement_completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('procurements_booking_id_fkey')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('procurements_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurements_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('procurements_booking_id_key'))
    )
    op.create_table('queue_tokens',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('queue_tokens_booking_id_fkey')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('queue_tokens_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_tokens_pkey')),
    sa.UniqueConstraint('centre_id', 'queue_date', 'token_number', name='uq_queue_tokens_centre_date_number')
    )
    op.create_index('idx_queue_tokens_centre_date_status', 'queue_tokens', ['centre_id', 'queue_date', 'status'], unique=False)
    op.create_table('wait_time_history',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('processing_start_time', sa.DateTime(), nullable=False),
    sa.Column('wait_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('wait_time_history_booking_id_fkey')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('wait_time_history_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wait_time_history_pkey'))
    )
    op.create_table('payments',
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], name=op.f('payments_procurement_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('procurement_id', name=op.f('payments_procurement_id_key'))
    )
    op.create_table('queue_events',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('queue_events_performed_by_fkey')),
    sa.ForeignKeyConstraint(['token_id'], ['queue_tokens.id'], name=op.f('queue_events_token_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_events_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_events')
    op.drop_table('payments')
    op.drop_table('wait_time_history')
    op.drop_index('idx_queue_tokens_centre_date_status', table_name='queue_tokens')
    op.drop_table('queue_tokens')
    op.drop_table('procurements')
    op.drop_table('processing_history')
    op.drop_table('notifications')
    op.drop_table('farmer_crops')
    op.drop_index('idx_bookings_farmer_status', table_name='bookings')
    op.drop_index('idx_bookings_centre_slot', table_name='bookings')
    op.drop_index(op.f('bookings_booking_reference_idx'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_slots_centre_date_time', table_name='slots')
    op.drop_table('slots')
    op.drop_index('idx_predictions_centre_for', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('officers')
    op.drop_table('farmers')
    op.drop_table('centre_metrics')
    op.drop_table('centre_capacity')
    op.drop_table('audit_logs')
    op.drop_index(op.f('users_phone_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('crops_code_idx'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('centres_code_idx'), table_name='centres')
    op.drop_table('centres')
    # ### end Alembic commands ###
