"""crop_taxonomy

Revision ID: d3ed2a7fdc70
Revises: 8fb27180134a
Create Date: 2026-09-02 10:52:23.370297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ed2a7fdc70'
down_revision: Union[str, Sequence[str], None] = '8fb27180134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crop_categories_pkey'))
    )
    op.create_index(op.f('crop_categories_code_idx'), 'crop_categories', ['code'], unique=True)
    op.create_table('crop_types',
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_kind', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('crop_types_crop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crop_types_pkey'))
    )
    op.create_index(op.f('crop_types_code_idx'), 'crop_types', ['code'], unique=True)
    op.add_column('crops', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('crops', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('crops_category_id_fkey'), 'crops', 'crop_categories', ['category_id'], ['id'])
    op.add_column('farmer_crops', sa.Column('crop_type_id', sa.UUID(), nullable=True))
    op.add_column('farmer_crops', sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('farmer_crops', sa.Column('unit', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('uq_farmer_crop_season'), 'farmer_crops', type_='unique')
    op.create_unique_constraint('uq_farmer_crop_season_type', 'farmer_crops', ['farmer_id', 'crop_id', 'season', 'crop_type_id'])
    op.create_foreign_key(op.f('farmer_crops_crop_type_id_fkey'), 'farmer_crops', 'crop_types', ['crop_type_id'], ['id'])
    op.drop_column('farmer_crops', 'estimated_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_crops', sa.Column('estimated_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('farmer_crops_crop_type_id_fkey'), 'farmer_crops', type_='foreignkey')
    op.drop_constraint('uq_farmer_crop_season_type', 'farmer_crops', type_='unique')
    op.create_unique_constraint(op.f('uq_farmer_crop_season'), 'farmer_crops', ['farmer_id', 'crop_id', 'season'], postgresql_nulls_not_distinct=False)
    op.drop_column('farmer_crops', 'unit')
    op.drop_column('farmer_crops', 'quantity')
    op.drop_column('farmer_crops', 'crop_type_id')
    op.drop_constraint(op.f('crops_category_id_fkey'), 'crops', type_='foreignkey')
    op.drop_column('crops', 'description')
    op.drop_column('crops', 'category_id')
    op.drop_index(op.f('crop_types_code_idx'), table_name='crop_types')
    op.drop_table('crop_types')
    op.drop_index(op.f('crop_categories_code_idx'), table_name='crop_categories')
    op.drop_table('crop_categories')
    # ### end Alembic commands ###
