import { CropInfo, FarmerProfile, ProcurementCentre, TokenRecord } from './types';

export const MOCK_FARMER: FarmerProfile = {
  id: 'FARM-PB-2026-891',
  name: 'Gurpreet Singh Dhillon',
  hindiName: 'गुरप्रीत सिंह ढिल्लों',
  punjabiName: 'ਗੁਰਪ੍ਰੀਤ ਸਿੰਘ ਢਿੱਲੋਂ',
  phone: '+91 98765 43210',
  aadhaarMasked: 'XXXX-XXXX-4819',
  farmerId: 'PMK-2024-PB-99412',
  state: 'Punjab',
  district: 'Ludhiana',
  village: 'Bija, Khanna Tehsil',
  landAcres: 14.5,
  bankAccountMasked: 'HDFC •••• 9104',
  bankName: 'HDFC Bank (Khanna Branch)',
  ifsc: 'HDFC0001248',
};

export const CROPS_CATALOG: CropInfo[] = [
  {
    id: 'crop-wheat',
    name: 'Wheat (Kanak / Gehu)',
    hindiName: 'गेहूं (कनक)',
    punjabiName: 'ਕਣਕ (ਗੇਹੂੰ)',
    category: 'Rabi',
    mspPerQuintal: 2275,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-paddy-a',
    name: 'Paddy Grade A (Dhan)',
    hindiName: 'धान ग्रेड-ए',
    punjabiName: 'ਝੋਨਾ ਗ੍ਰੇਡ-ਏ',
    category: 'Kharif',
    mspPerQuintal: 2320,
    maxMoisturePct: 17.0,
    standardBagWeightKg: 50,
    icon: '🌱',
  },
  {
    id: 'crop-mustard',
    name: 'Mustard / Rapeseed (Sarson)',
    hindiName: 'सरसों',
    punjabiName: 'ਸਰ੍ਹੋਂ',
    category: 'Rabi',
    mspPerQuintal: 5650,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌼',
  },
  {
    id: 'crop-chana',
    name: 'Gram / Chickpea (Chana)',
    hindiName: 'चना',
    punjabiName: 'ਛੋਲੇ / ਚਨਾ',
    category: 'Rabi',
    mspPerQuintal: 5440,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🫘',
  },
  {
    id: 'crop-soyabean',
    name: 'Soyabean (Yellow)',
    hindiName: 'सोयाबीन (पीला)',
    punjabiName: 'ਸੋਇਆਬੀਨ',
    category: 'Kharif',
    mspPerQuintal: 4892,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌿',
  },
];

export const INITIAL_CENTRES: ProcurementCentre[] = [
  {
    id: 'centre-samrala',
    name: 'Samrala Sub-Mandi Procurement Depot',
    code: 'PB-LDH-042',
    district: 'Ludhiana',
    state: 'Punjab',
    distanceKm: 8.4,
    currentQueueCount: 3,
    avgWaitMinutes: 18,
    yardCapacityPercent: 32,
    activeBays: 4,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 10,
    isAiRecommended: true,
    recommendedReason: 'System Recommended: Fast turnaround (18 mins wait), covered bays & lowest yard congestion.',
  },
  {
    id: 'centre-khanna',
    name: 'Khanna APMC Grain Market (Asia Yard 1)',
    code: 'PB-LDH-001',
    district: 'Ludhiana',
    state: 'Punjab',
    distanceKm: 5.2,
    currentQueueCount: 19,
    avgWaitMinutes: 85,
    yardCapacityPercent: 78,
    activeBays: 6,
    status: 'CONGESTED',
    weatherCondition: 'Partly Cloudy • 29°C',
    rainRiskPercent: 25,
    isAiRecommended: false,
    recommendedReason: 'High arrival volume. Diversion recommended to avoid yard choking.',
  },
  {
    id: 'centre-doraha',
    name: 'Doraha FCI Storage Godown Center',
    code: 'PB-LDH-019',
    district: 'Ludhiana',
    state: 'Punjab',
    distanceKm: 14.1,
    currentQueueCount: 26,
    avgWaitMinutes: 130,
    yardCapacityPercent: 91,
    activeBays: 3,
    status: 'CONGESTED',
    weatherCondition: 'Cloudy • 27°C',
    rainRiskPercent: 45,
    isAiRecommended: false,
    recommendedReason: 'Heavy bottleneck at weighbridge #1. Avoid booking for afternoon slot.',
  },
  {
    id: 'centre-sahnewal',
    name: 'Sahnewal Modern Silo Complex',
    code: 'PB-LDH-088',
    district: 'Ludhiana',
    state: 'Punjab',
    distanceKm: 19.5,
    currentQueueCount: 6,
    avgWaitMinutes: 28,
    yardCapacityPercent: 45,
    activeBays: 5,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 15,
    isAiRecommended: false,
  },
];

export const INITIAL_TOKENS: TokenRecord[] = [
  {
    id: 'token-01',
    tokenNumber: 'KF-2026-0942',
    farmerId: 'FARM-PB-2026-891',
    farmerName: 'Gurpreet Singh Dhillon',
    phone: '+91 98765 43210',
    village: 'Bija, Khanna Tehsil',
    cropId: 'crop-wheat',
    cropName: 'Wheat (Kanak / Gehu)',
    estimatedQuintals: 45,
    centreId: 'centre-samrala',
    centreName: 'Samrala Sub-Mandi Procurement Depot',
    slotDate: '2026-09-05',
    slotTime: '09:30 AM - 10:30 AM',
    vehicleType: 'Tractor Trolley',
    vehicleNumber: 'PB-10-DF-4819',
    status: 'WEIGHBRIDGE_IN',
    assignedBay: 'Bay 2 (Electronic Weighbridge)',
    createdAt: '2026-09-05T07:15:00Z',
    updatedAt: '2026-09-05T09:25:00Z',
    qrCodeValue: 'KISANFLOW://TOKEN/KF-2026-0942/PB-10-DF-4819',
    smsAlerts: [
      {
        id: 'sms-1',
        timestamp: '07:15 AM',
        text: 'KisanFlow: e-Gate Pass KF-2026-0942 confirmed for Samrala Depot. Entry Slot: 09:30 AM. Present QR at Gate 1.',
        type: 'BOOKING',
      },
      {
        id: 'sms-2',
        timestamp: '09:15 AM',
        text: 'KisanFlow: Gate 1 passed. Token called! Proceed immediately to Weighbridge Bay 2.',
        type: 'BAY_CALL',
      },
    ],
  },
  {
    id: 'token-02',
    tokenNumber: 'KF-2026-0940',
    farmerId: 'FARM-PB-2026-712',
    farmerName: 'Harbhajan Singh Gill',
    phone: '+91 98111 22334',
    village: 'Khatra, Samrala',
    cropId: 'crop-wheat',
    cropName: 'Wheat (Kanak / Gehu)',
    estimatedQuintals: 52,
    centreId: 'centre-samrala',
    centreName: 'Samrala Sub-Mandi Procurement Depot',
    slotDate: '2026-09-05',
    slotTime: '08:30 AM - 09:30 AM',
    vehicleType: 'Tractor Trolley',
    vehicleNumber: 'PB-23-J-9912',
    status: 'COMPLETED',
    assignedBay: 'Bay 1 (Unloading Platform)',
    qualityReport: {
      moisturePct: 11.4,
      foreignMatterPct: 0.4,
      brokenGrainPct: 1.2,
      grade: 'FAQ_GRADE_A',
      deductionsAppliedRs: 0,
      inspectorName: 'Er. R. K. Sharma (QCO-IV)',
      inspectedAt: '09:02 AM',
      passed: true,
      notes: 'Grain luster excellent, moisture well within 12.0% Fair Average Quality norm.',
    },
    paymentDetails: {
      grossWeightKg: 8420,
      tareWeightKg: 3220,
      netWeightQuintals: 52.0,
      mspRatePerQuintal: 2275,
      grossAmountRs: 118300,
      qualityDeductionsRs: 0,
      mandiFeesRs: 0,
      netPayableRs: 118300,
      utrNumber: 'RBI-DBT-20260905-99812401',
      paymentStatus: 'PAID_TO_BANK',
      paidAt: '09:35 AM',
      jFormNumber: 'JF-PB-SAM-2026-0814',
    },
    createdAt: '2026-09-05T06:30:00Z',
    updatedAt: '2026-09-05T09:35:00Z',
    qrCodeValue: 'KISANFLOW://TOKEN/KF-2026-0940/PB-23-J-9912',
    smsAlerts: [
      {
        id: 'sms-02-1',
        timestamp: '09:35 AM',
        text: 'KisanFlow: Digital J-Form #JF-PB-SAM-2026-0814 issued. MSP Payout of ₹1,18,300 transferred via DBT (UTR: RBI-DBT-20260905-99812401).',
        type: 'PAYMENT',
      },
    ],
  },
  {
    id: 'token-03',
    tokenNumber: 'KF-2026-0945',
    farmerId: 'FARM-PB-2026-621',
    farmerName: 'Balwinder Kaur',
    phone: '+91 94170 88776',
    village: 'Machhiwara, Ludhiana',
    cropId: 'crop-mustard',
    cropName: 'Mustard / Rapeseed (Sarson)',
    estimatedQuintals: 28,
    centreId: 'centre-samrala',
    centreName: 'Samrala Sub-Mandi Procurement Depot',
    slotDate: '2026-09-05',
    slotTime: '10:00 AM - 11:00 AM',
    vehicleType: 'Mini Truck',
    vehicleNumber: 'PB-10-EA-1922',
    status: 'YARD_QUEUED',
    createdAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-05T08:45:00Z',
    qrCodeValue: 'KISANFLOW://TOKEN/KF-2026-0945/PB-10-EA-1922',
    smsAlerts: [
      {
        id: 'sms-03-1',
        timestamp: '08:45 AM',
        text: 'KisanFlow: Entered yard queue at Samrala Depot. Estimated wait: 14 minutes.',
        type: 'GATE_ENTRY',
      },
    ],
  },
  {
    id: 'token-04',
    tokenNumber: 'KF-2026-0948',
    farmerId: 'FARM-PB-2026-440',
    farmerName: 'Manmohan Singh',
    phone: '+91 97799 12345',
    village: 'Alour, Khanna',
    cropId: 'crop-wheat',
    cropName: 'Wheat (Kanak / Gehu)',
    estimatedQuintals: 65,
    centreId: 'centre-samrala',
    centreName: 'Samrala Sub-Mandi Procurement Depot',
    slotDate: '2026-09-05',
    slotTime: '10:30 AM - 11:30 AM',
    vehicleType: 'Tractor Trolley',
    vehicleNumber: 'PB-10-CH-7789',
    status: 'BOOKED',
    createdAt: '2026-09-05T08:30:00Z',
    updatedAt: '2026-09-05T08:30:00Z',
    qrCodeValue: 'KISANFLOW://TOKEN/KF-2026-0948/PB-10-CH-7789',
    smsAlerts: [],
  },
];
