import { CropInfo, FarmerProfile, ProcurementCentre, TokenRecord } from './types';

export const MOCK_FARMER: FarmerProfile = {
  id: 'FARM-PB-2026-007',
  name: 'Mahendra Singh Dhoni',
  hindiName: 'महेंद्र सिंह धोनी',
  punjabiName: 'ਮਹਿੰਦਰ ਸਿੰਘ ਧੋਨੀ',
  phone: '+91 97714 00007',
  aadhaarMasked: 'XXXX-XXXX-0007',
  farmerId: 'PMK-2026-PB-00007',
  state: 'Punjab',
  district: 'Ludhiana',
  village: 'Samrala Agri Farm',
  landAcres: 18.5,
  bankAccountMasked: 'SBI •••• 0007',
  bankName: 'State Bank of India (Samrala Branch)',
  ifsc: 'SBIN0001248',
};

export const CROPS_CATALOG: CropInfo[] = [
  {
    id: 'crop-wheat',
    name: 'Wheat (Kanak / Gehu)',
    hindiName: 'गेहूं (कनक)',
    punjabiName: 'ਕਣਕ (ਗੇਹੂੰ)',
    category: 'Rabi',
    mspPerQuintal: 2275,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-paddy-a',
    name: 'Paddy Grade A (Dhan)',
    hindiName: 'धान ग्रेड-ए',
    punjabiName: 'ਝੋਨਾ ਗ੍ਰੇਡ-ਏ',
    category: 'Kharif',
    mspPerQuintal: 2320,
    maxMoisturePct: 17.0,
    standardBagWeightKg: 50,
    icon: '🌱',
  },
  {
    id: 'crop-mustard',
    name: 'Mustard / Rapeseed (Sarson)',
    hindiName: 'सरसों',
    punjabiName: 'ਸਰ੍ਹੋਂ',
    category: 'Rabi',
    mspPerQuintal: 5650,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌼',
  },
  {
    id: 'crop-chana',
    name: 'Gram / Chickpea (Chana)',
    hindiName: 'चना',
    punjabiName: 'ਛੋਲੇ / ਚਨਾ',
    category: 'Rabi',
    mspPerQuintal: 5440,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🫘',
  },
  {
    id: 'crop-soyabean',
    name: 'Soyabean (Yellow)',
    hindiName: 'सोयाबीन (पीला)',
    punjabiName: 'ਸੋਇਆਬੀਨ',
    category: 'Kharif',
    mspPerQuintal: 4892,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌿',
  },
];

export const INITIAL_CENTRES: ProcurementCentre[] = [
  {
    id: 'centre-samrala',
    name: 'Samrala Sub-Mandi Procurement Depot',
    code: 'PB-LDH-042',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Near Old Bus Stand, Samrala Bypass Road, Samrala, Punjab 141114',
    latitude: 30.8359,
    longitude: 76.1914,
    distanceKm: 8.4,
    transitMinutes: 20,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8359,76.1914',
    currentQueueCount: 3,
    avgWaitMinutes: 18,
    yardCapacityPercent: 32,
    activeBays: 4,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 10,
    isAiRecommended: true,
    recommendedReason: 'System Recommended: Fast turnaround (18 mins wait), covered bays & lowest yard congestion.',
  },
  {
    id: 'centre-khanna',
    name: 'Khanna APMC Grain Market (Asia Yard 1)',
    code: 'PB-LDH-001',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Grand Trunk Road, Asia Grain Yard Block A, Khanna, Punjab 141401',
    latitude: 30.7068,
    longitude: 76.2205,
    distanceKm: 5.2,
    transitMinutes: 15,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.7068,76.2205',
    currentQueueCount: 19,
    avgWaitMinutes: 85,
    yardCapacityPercent: 78,
    activeBays: 6,
    status: 'CONGESTED',
    weatherCondition: 'Partly Cloudy • 29°C',
    rainRiskPercent: 25,
    isAiRecommended: false,
    recommendedReason: 'High arrival volume. Diversion recommended to avoid yard choking.',
  },
  {
    id: 'centre-doraha',
    name: 'Doraha FCI Storage Godown Center',
    code: 'PB-LDH-019',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'NH-44 Highway Link, Doraha Rail Terminal, Doraha, Punjab 141421',
    latitude: 30.8052,
    longitude: 76.0354,
    distanceKm: 14.1,
    transitMinutes: 34,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8052,76.0354',
    currentQueueCount: 26,
    avgWaitMinutes: 130,
    yardCapacityPercent: 91,
    activeBays: 3,
    status: 'CONGESTED',
    weatherCondition: 'Cloudy • 27°C',
    rainRiskPercent: 45,
    isAiRecommended: false,
    recommendedReason: 'Heavy bottleneck at weighbridge #1. Avoid booking for afternoon slot.',
  },
  {
    id: 'centre-sahnewal',
    name: 'Sahnewal Modern Silo Complex',
    code: 'PB-LDH-088',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Airport Road, Near Dry Port Inland Container Depot, Sahnewal, Punjab 141120',
    latitude: 30.8444,
    longitude: 75.9806,
    distanceKm: 19.5,
    transitMinutes: 42,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8444,75.9806',
    currentQueueCount: 6,
    avgWaitMinutes: 28,
    yardCapacityPercent: 45,
    activeBays: 5,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 15,
    isAiRecommended: false,
    recommendedReason: 'Smooth traffic intake and automated pneumatic unloading operational.',
  },
  {
    id: 'centre-ludhiana-main',
    name: 'Ludhiana Central Nodal Mandi Hub',
    code: 'PB-LDH-105',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Ferozepur Road Procurement Yard, Ludhiana, Punjab 141001',
    latitude: 30.9010,
    longitude: 75.8573,
    distanceKm: 27.8,
    transitMinutes: 55,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.9010,75.8573',
    currentQueueCount: 11,
    avgWaitMinutes: 40,
    yardCapacityPercent: 52,
    activeBays: 8,
    status: 'OPEN',
    weatherCondition: 'Hazy Sun • 29°C',
    rainRiskPercent: 12,
    isAiRecommended: false,
    recommendedReason: 'High capacity hub with 8 automated weighbridges for large trailer loads.',
  },
];

export const INITIAL_TOKENS: TokenRecord[] = [];


