import { CropInfo, FarmerProfile, ProcurementCentre, TokenRecord } from './types';

export const MOCK_FARMER: FarmerProfile = {
  id: 'FARM-PB-2026-007',
  name: 'Mahendra Singh Dhoni',
  hindiName: 'महेंद्र सिंह धोनी',
  punjabiName: 'ਮਹਿੰਦਰ ਸਿੰਘ ਧੋਨੀ',
  phone: '+91 97714 00007',
  aadhaarMasked: 'XXXX-XXXX-0007',
  farmerId: 'PMK-2026-PB-00007',
  state: 'Punjab',
  district: 'Ludhiana',
  village: 'Samrala Agri Farm',
  landAcres: 18.5,
  bankAccountMasked: 'SBI •••• 0007',
  bankName: 'State Bank of India (Samrala Branch)',
  ifsc: 'SBIN0001248',
};

export const CROPS_CATALOG: CropInfo[] = [
  // CEREALS & FOOD GRAINS
  {
    id: 'crop-wheat',
    name: 'Wheat (Sharbati / PBW-725)',
    hindiName: 'गेहूं (शरबती)',
    punjabiName: 'ਕਣਕ (ਸ਼ਰਬਤੀ)',
    category: 'Rabi',
    mspPerQuintal: 2275,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-paddy-a',
    name: 'Paddy Grade A (Basmati PB-1121)',
    hindiName: 'धान ग्रेड-ए (बासमती)',
    punjabiName: 'ਝੋਨਾ ਗ੍ਰੇਡ-ਏ (ਬਾਸਮਤੀ)',
    category: 'Kharif',
    mspPerQuintal: 2320,
    maxMoisturePct: 17.0,
    standardBagWeightKg: 50,
    icon: '🍚',
  },
  {
    id: 'crop-paddy-common',
    name: 'Paddy Common (Parmal / PR-126)',
    hindiName: 'धान सामान्य (परमल)',
    punjabiName: 'ਝੋਨਾ ਆਮ (ਪਰਮਲ)',
    category: 'Kharif',
    mspPerQuintal: 2300,
    maxMoisturePct: 17.0,
    standardBagWeightKg: 50,
    icon: '🌱',
  },
  {
    id: 'crop-maize',
    name: 'Yellow Maize (Makki - K-65)',
    hindiName: 'मक्का (पीला)',
    punjabiName: 'ਮੱਕੀ (ਪੀਲੀ)',
    category: 'Kharif',
    mspPerQuintal: 2090,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🌽',
  },
  {
    id: 'crop-barley',
    name: 'Barley (Jau - DWRB-123)',
    hindiName: 'जौ (देसी)',
    punjabiName: 'ਜੌਂ (ਸਾਬਤ)',
    category: 'Rabi',
    mspPerQuintal: 1850,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },

  // SHREE ANNA / MILLETS
  {
    id: 'crop-bajra',
    name: 'Bajra (Pearl Millet - HHB-67)',
    hindiName: 'बाजरा',
    punjabiName: 'ਬਾਜਰਾ (ਮੋਟਾ ਅਨਾਜ)',
    category: 'Kharif',
    mspPerQuintal: 2500,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-jowar',
    name: 'Jowar (Sorghum / Maldandi)',
    hindiName: 'ज्वार (मालदंडी)',
    punjabiName: 'ਜਵਾਰ (ਚਰੀ)',
    category: 'Kharif',
    mspPerQuintal: 3180,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-ragi',
    name: 'Ragi (Finger Millet - Mandua)',
    hindiName: 'रागी (मंडुआ)',
    punjabiName: 'ਰਾਗੀ / ਕੋਧਰਾ',
    category: 'Kharif',
    mspPerQuintal: 3846,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-kodo',
    name: 'Kodo Millet (Kodra - Shree Anna)',
    hindiName: 'कोदो (श्रीअन्न)',
    punjabiName: 'ਕੋਦੋ ਮਿਲਟ',
    category: 'Kharif',
    mspPerQuintal: 3500,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🥣',
  },
  {
    id: 'crop-foxtail',
    name: 'Kangni / Foxtail Millet (Kakun)',
    hindiName: 'कांगणी (ककुन)',
    punjabiName: 'ਕੰਗਣੀ (ਸ੍ਰੀ ਅੰਨ)',
    category: 'Kharif',
    mspPerQuintal: 3800,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },

  // PULSES & LEGUMES
  {
    id: 'crop-chana',
    name: 'Gram / Chickpea (Desi & Kabuli)',
    hindiName: 'चना (देसी/काबुली)',
    punjabiName: 'ਛੋਲੇ / ਚਨਾ (ਦੇਸੀ)',
    category: 'Rabi',
    mspPerQuintal: 5440,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🫘',
  },
  {
    id: 'crop-moong',
    name: 'Moong Dal (Green Gram - SML-668)',
    hindiName: 'मूंग दाल',
    punjabiName: 'ਮੂੰਗ ਦਾਲ (ਸਾਬਤ)',
    category: 'Kharif',
    mspPerQuintal: 8558,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🌿',
  },
  {
    id: 'crop-urad',
    name: 'Urad Dal (Black Gram - Mash-114)',
    hindiName: 'उड़द दाल (माश)',
    punjabiName: 'ਮਾਂਹ / ਉੜਦ ਦਾਲ',
    category: 'Kharif',
    mspPerQuintal: 6950,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 50,
    icon: '⚫',
  },
  {
    id: 'crop-arhar',
    name: 'Arhar / Tur (Pigeon Pea - UPAS-120)',
    hindiName: 'अरहर / तूर दाल',
    punjabiName: 'ਤੂਰ / ਅਰਹਰ ਦਾਲ',
    category: 'Kharif',
    mspPerQuintal: 7000,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 50,
    icon: '🍲',
  },
  {
    id: 'crop-masur',
    name: 'Masur (Red Lentil - Malika)',
    hindiName: 'मसूर दाल',
    punjabiName: 'ਮਸਰਾਂ ਦੀ ਦਾਲ',
    category: 'Rabi',
    mspPerQuintal: 6425,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 50,
    icon: '🥣',
  },
  {
    id: 'crop-moth',
    name: 'Moth Bean (Moth Dal / Maru)',
    hindiName: 'मूँठ दाल',
    punjabiName: 'ਮੋਠ ਦਾਲ',
    category: 'Kharif',
    mspPerQuintal: 5800,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 50,
    icon: '🫘',
  },
  {
    id: 'crop-rajma',
    name: 'Rajma (Red Kidney Beans)',
    hindiName: 'राजमा (चित्र/लाल)',
    punjabiName: 'ਰਾਜਮਾਹ',
    category: 'Kharif',
    mspPerQuintal: 9500,
    maxMoisturePct: 11.0,
    standardBagWeightKg: 50,
    icon: '🫘',
  },

  // OILSEEDS
  {
    id: 'crop-mustard',
    name: 'Mustard / Sarson (Giriraj / Pusa-31)',
    hindiName: 'सरसों (पीली/काली)',
    punjabiName: 'ਸਰ੍ਹੋਂ (ਪੀਲੀ/ਕਾਲੀ)',
    category: 'Rabi',
    mspPerQuintal: 5650,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌼',
  },
  {
    id: 'crop-soybean',
    name: 'Soybean (Yellow - Pusa-9712)',
    hindiName: 'सोयाबीन (पीला)',
    punjabiName: 'ਸੋਇਆਬੀਨ (ਪੀਲੀ)',
    category: 'Kharif',
    mspPerQuintal: 4892,
    maxMoisturePct: 12.0,
    standardBagWeightKg: 50,
    icon: '🥜',
  },
  {
    id: 'crop-groundnut',
    name: 'Groundnut-in-shell (Mungphali)',
    hindiName: 'मूंगफली (छिलके सहित)',
    punjabiName: 'ਮੂੰਗਫਲੀ (ਸਾਬਤ)',
    category: 'Kharif',
    mspPerQuintal: 6377,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌰',
  },
  {
    id: 'crop-sunflower',
    name: 'Sunflower Seed (Surajmukhi)',
    hindiName: 'सूरजमुखी बीज',
    punjabiName: 'ਸੂਰਜਮੁਖੀ ਬੀਜ',
    category: 'Kharif',
    mspPerQuintal: 6760,
    maxMoisturePct: 9.0,
    standardBagWeightKg: 50,
    icon: '🌻',
  },
  {
    id: 'crop-sesamum',
    name: 'Sesamum / Til (White & Black)',
    hindiName: 'तिल (सफेद व काला)',
    punjabiName: 'ਤਿਲ (ਚਿੱਟੇ/ਕਾਲੇ)',
    category: 'Kharif',
    mspPerQuintal: 8635,
    maxMoisturePct: 9.0,
    standardBagWeightKg: 50,
    icon: '⚪',
  },
  {
    id: 'crop-safflower',
    name: 'Safflower / Kardi (Kusum)',
    hindiName: 'कुसुम (करडी)',
    punjabiName: 'ਕੁਸੁਮ ਬੀਜ',
    category: 'Rabi',
    mspPerQuintal: 5800,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌼',
  },
  {
    id: 'crop-niger',
    name: 'Niger Seed (Ramtil)',
    hindiName: 'रामतिल',
    punjabiName: 'ਰਾਮਤਿਲ',
    category: 'Kharif',
    mspPerQuintal: 7734,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌻',
  },
  {
    id: 'crop-castor',
    name: 'Castor Seed (Arandi)',
    hindiName: 'अरंडी (एरंड)',
    punjabiName: 'ਅਰੰਡੀ ਬੀਜ',
    category: 'Kharif',
    mspPerQuintal: 5950,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌰',
  },

  // COMMERCIAL & CASH CROPS
  {
    id: 'crop-cotton',
    name: 'Raw Cotton (Medium Staple / Narma)',
    hindiName: 'कपास / नरमा (मध्यम रेशा)',
    punjabiName: 'ਕਪਾਹ / ਨਰਮਾ',
    category: 'Commercial',
    mspPerQuintal: 6620,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '☁️',
  },
  {
    id: 'crop-cotton-long',
    name: 'Raw Cotton (Long Staple H-4)',
    hindiName: 'कपास (लंबा रेशा शंकर)',
    punjabiName: 'ਲੰਬੀ ਰੇਸ਼ੇ ਵਾਲੀ ਕਪਾਹ',
    category: 'Commercial',
    mspPerQuintal: 7020,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '☁️',
  },
  {
    id: 'crop-sugarcane',
    name: 'Sugarcane (FRP Mill Gate Co-0238)',
    hindiName: 'गन्ना (मिल गेट)',
    punjabiName: 'ਗੰਨਾ (ਕਮਾਦ)',
    category: 'Commercial',
    mspPerQuintal: 340,
    maxMoisturePct: 70.0,
    standardBagWeightKg: 100,
    icon: '🎋',
  },
  {
    id: 'crop-jute',
    name: 'Raw Jute / Patson (TD-5)',
    hindiName: 'कच्चा पटसन (जूट TD-5)',
    punjabiName: 'ਪਟਸਨ / ਜੂਟ',
    category: 'Commercial',
    mspPerQuintal: 5050,
    maxMoisturePct: 18.0,
    standardBagWeightKg: 50,
    icon: '🧶',
  },
  {
    id: 'crop-copra',
    name: 'Copra Milling (Gola / Coconut)',
    hindiName: 'खोपरा / सूखा नारियल',
    punjabiName: 'ਸੁੱਕਾ ਨਾਰੀਅਲ (ਖੋਪਰਾ)',
    category: 'Commercial',
    mspPerQuintal: 11160,
    maxMoisturePct: 6.0,
    standardBagWeightKg: 50,
    icon: '🥥',
  },

  // SPICES & HIGH-VALUE APMC
  {
    id: 'crop-turmeric',
    name: 'Turmeric (Haldi - Nizamabad)',
    hindiName: 'हल्दी (निजामाबाद)',
    punjabiName: 'ਹਲਦੀ (ਸਾਬਤ)',
    category: 'Spices',
    mspPerQuintal: 13500,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 50,
    icon: '🟡',
  },
  {
    id: 'crop-chilli',
    name: 'Red Chilli (Lal Mirch - Guntur)',
    hindiName: 'लाल मिर्च (गुंटूर तेजा)',
    punjabiName: 'ਲਾਲ ਮਿਰਚ',
    category: 'Spices',
    mspPerQuintal: 18000,
    maxMoisturePct: 10.0,
    standardBagWeightKg: 40,
    icon: '🌶️',
  },
  {
    id: 'crop-coriander',
    name: 'Coriander Seed (Dhania Badami)',
    hindiName: 'धनिया बीज (बादामी)',
    punjabiName: 'ਧਨੀਆ ਬੀਜ',
    category: 'Spices',
    mspPerQuintal: 7200,
    maxMoisturePct: 9.0,
    standardBagWeightKg: 40,
    icon: '🌿',
  },
  {
    id: 'crop-jeera',
    name: 'Cumin / Jeera (Unjha Super)',
    hindiName: 'जीरा (ऊंझा सुपर)',
    punjabiName: 'ਜੀਰਾ',
    category: 'Spices',
    mspPerQuintal: 24500,
    maxMoisturePct: 8.0,
    standardBagWeightKg: 50,
    icon: '🌾',
  },
  {
    id: 'crop-garlic',
    name: 'Garlic (Lahsun - Mandsaur Bold)',
    hindiName: 'लहसुन (मंदसौर)',
    punjabiName: 'ਲਸਣ (ਗੰਢੇ)',
    category: 'Spices',
    mspPerQuintal: 12000,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🧄',
  },

  // MANDI VEGETABLES & HORTICULTURE
  {
    id: 'crop-onion',
    name: 'Onion (Pyaz - Nashik Red)',
    hindiName: 'प्याज (नासिक लाल)',
    punjabiName: 'ਗੰਢੇ / ਪਿਆਜ਼ (ਲਾਲ)',
    category: 'Horticulture',
    mspPerQuintal: 1850,
    maxMoisturePct: 14.0,
    standardBagWeightKg: 50,
    icon: '🧅',
  },
  {
    id: 'crop-potato',
    name: 'Potato (Aloo - Kufri Pukhraj)',
    hindiName: 'आलू (कुफरी पुखराज)',
    punjabiName: 'ਆਲੂ (ਪੁਖਰਾਜ)',
    category: 'Horticulture',
    mspPerQuintal: 1450,
    maxMoisturePct: 18.0,
    standardBagWeightKg: 50,
    icon: '🥔',
  },
];

export const INITIAL_CENTRES: ProcurementCentre[] = [
  {
    id: 'centre-samrala',
    name: 'Samrala Sub-Mandi Procurement Depot',
    code: 'PB-LDH-042',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Near Old Bus Stand, Samrala Bypass Road, Samrala, Punjab 141114',
    latitude: 30.8359,
    longitude: 76.1914,
    distanceKm: 8.4,
    transitMinutes: 20,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8359,76.1914',
    currentQueueCount: 3,
    avgWaitMinutes: 18,
    yardCapacityPercent: 32,
    activeBays: 4,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 10,
    isAiRecommended: true,
    recommendedReason: 'System Recommended: Fast turnaround (18 mins wait), covered bays & lowest yard congestion.',
  },
  {
    id: 'centre-khanna',
    name: 'Khanna APMC Grain Market (Asia Yard 1)',
    code: 'PB-LDH-001',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Grand Trunk Road, Asia Grain Yard Block A, Khanna, Punjab 141401',
    latitude: 30.7068,
    longitude: 76.2205,
    distanceKm: 5.2,
    transitMinutes: 15,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.7068,76.2205',
    currentQueueCount: 19,
    avgWaitMinutes: 85,
    yardCapacityPercent: 78,
    activeBays: 6,
    status: 'CONGESTED',
    weatherCondition: 'Partly Cloudy • 29°C',
    rainRiskPercent: 25,
    isAiRecommended: false,
    recommendedReason: 'High arrival volume. Diversion recommended to avoid yard choking.',
  },
  {
    id: 'centre-doraha',
    name: 'Doraha FCI Storage Godown Center',
    code: 'PB-LDH-019',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'NH-44 Highway Link, Doraha Rail Terminal, Doraha, Punjab 141421',
    latitude: 30.8052,
    longitude: 76.0354,
    distanceKm: 14.1,
    transitMinutes: 34,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8052,76.0354',
    currentQueueCount: 26,
    avgWaitMinutes: 130,
    yardCapacityPercent: 91,
    activeBays: 3,
    status: 'CONGESTED',
    weatherCondition: 'Cloudy • 27°C',
    rainRiskPercent: 45,
    isAiRecommended: false,
    recommendedReason: 'Heavy bottleneck at weighbridge #1. Avoid booking for afternoon slot.',
  },
  {
    id: 'centre-sahnewal',
    name: 'Sahnewal Modern Silo Complex',
    code: 'PB-LDH-088',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Airport Road, Near Dry Port Inland Container Depot, Sahnewal, Punjab 141120',
    latitude: 30.8444,
    longitude: 75.9806,
    distanceKm: 19.5,
    transitMinutes: 42,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.8444,75.9806',
    currentQueueCount: 6,
    avgWaitMinutes: 28,
    yardCapacityPercent: 45,
    activeBays: 5,
    status: 'OPEN',
    weatherCondition: 'Clear Sky • 28°C',
    rainRiskPercent: 15,
    isAiRecommended: false,
    recommendedReason: 'Smooth traffic intake and automated pneumatic unloading operational.',
  },
  {
    id: 'centre-ludhiana-main',
    name: 'Ludhiana Central Nodal Mandi Hub',
    code: 'PB-LDH-105',
    district: 'Ludhiana',
    state: 'Punjab',
    address: 'Ferozepur Road Procurement Yard, Ludhiana, Punjab 141001',
    latitude: 30.9010,
    longitude: 75.8573,
    distanceKm: 27.8,
    transitMinutes: 55,
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.9010,75.8573',
    currentQueueCount: 11,
    avgWaitMinutes: 40,
    yardCapacityPercent: 52,
    activeBays: 8,
    status: 'OPEN',
    weatherCondition: 'Hazy Sun • 29°C',
    rainRiskPercent: 12,
    isAiRecommended: false,
    recommendedReason: 'High capacity hub with 8 automated weighbridges for large trailer loads.',
  },
];

export const INITIAL_TOKENS: TokenRecord[] = [];


